# Generated by Django 3.1.7 on 2021-03-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='expired_date',
            field=models.DateField(),
        ),
    ]
