# Generated by Django 3.1.7 on 2021-03-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0004_actors_categories_shows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shows',
            options={'ordering': ['publishDate']},
        ),
    ]
