# Generated by Django 3.1.7 on 2021-03-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0006_auto_20210330_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
