# Generated by Django 3.1.7 on 2021-03-31 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0007_auto_20210330_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='bigPoster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shows',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
                ('date', models.URLField(blank=True, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApi.shows')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('show', 'season', 'episode')},
            },
        ),
    ]
