# Generated by Django 3.1.7 on 2021-03-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0008_auto_20210331_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
