# Generated by Django 3.1.7 on 2021-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0010_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='disLikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shows',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shows',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
