# Generated by Django 3.1.7 on 2021-04-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0013_auto_20210408_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shows',
            options={'ordering': ['publishDate', 'name']},
        ),
    ]
