# Generated by Django 3.1.7 on 2021-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0014_auto_20210409_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
